language: python
python:
- '3.6.5'
before_install:
- pip install codecov
- pip install coverage

install:
- pip install -r requirements.txt

script:
- coverage run tests/tests_tools.py

after_success:
- codecov
