name: graphkit-learn

run-name: ${{ github.actor }} is testing graphkit-learn out GitHub Actions ðŸš€

on: [ push, pull_request ]

jobs:
  CI-CentOS:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.8" ] # , "3.9", "3.10" ]
        container: [ "centos:7" ]

    container:
      image: ${{ matrix.container }}

    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v3

      - run: echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ðŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - run: echo "ðŸªµ The root directory of the checked-out repository is:"
      - run: echo $GITHUB_WORKSPACE
      - name: List files in the repository
        run: |
          pwd
          ls /
          printf "\nThe files contained in the repository (GITHUB_WORKSPACE):\n"
          ls $GITHUB_WORKSPACE
      - run: echo "ðŸ This job's status is ${{ job.status }}."

      - name: Install system-level dependencies
        run: |
          #%% lsb-core is required for actions/setup-python@v4:
          printf "\nInstalling redhat-lsb-core:\n"
          yum install -y redhat-lsb-core

      - name: Upgrade glibc
        run: |
          #%% Install a higher version of glibc: (The latest version on CentOS 7
          #%% is 2.17, while at least 2.34 is required for the latest Python 3.8.)
          # Determine the current version of glibc that is installed:
          printf "\nCurrent version of glibc installed:\n"
          rpm -q glibc
#
#          # Check if a newer version of glibc is available in the official CentOS
#          # repositories:
#          printf "\nThe latest version of glibc available on the current system:\n"
#          yum list glibc
#
##          # Installing it from a third-party repository such as the Fedora EPEL:
##          printf "\nInstalling Fedora EPEL:\n"
##          yes y | yum install epel-release
#
#          printf "\nInstalling the latest version of glibc from source:\n"
#          cd /usr/local/
#          mkdir softwares
#          cd softwares
#          pwd
#          git clone https://sourceware.org/git/glibc.git
#          cd glibc
#          git checkout master
#          mkdir build
#          cd build
#          ../configure --prefix=/usr/local/glibc-latest
#          make
#          make install
#          export LD_LIBRARY_PATH=/usr/local/glibc-latest/lib:$LD_LIBRARY_PATH
#          cd $GITHUB_WORKSPACE
#          pwd
#
#          # Verify that glibc has been installed:
#          printf "\nThe new version of glibc installed:\n"
#          rpm -q glibc

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
#          cache: 'pip' # caching pip dependencies

      - name: Check installed Python and pip
        run: |
          python --version
          pip --version
          find / -name pip 2>/dev/null

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Cython pytest
          pip install codecov coverage pytest-cov
          sudo apt-get -y install gfortran liblapack-dev
          pip install -r requirements.txt
          pip install wheel

      - name: Build and test
        run: |
          python setup.py bdist_wheel
          pytest -v --cov-config=.coveragerc --cov-report term --cov=gklearn gklearn/tests/ged/
      #          pytest -v --cov-config=.coveragerc --cov-report term --cov=gklearn gklearn/tests/ --ignore=gklearn/tests/test_median_preimage_generator.py --ignore=gklearn/tests/test_graphkernels.py

      - name: Run code coverage
        run: |
          codecov

#      - name: Publish distribution ðŸ“¦ to Test PyPI
#        if: matrix.python-version == '3.8' && matrix.os == 'ubuntu-latest'
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
#          repository-url: https://test.pypi.org/legacy/
#
#      - name: Publish distribution ðŸ“¦ to PyPI
#        if: matrix.python-version == '3.8' && matrix.os == 'ubuntu-latest'
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          user: __token__
#          password: ${{ secrets.PYPI_API_TOKEN }}